mkdir -p ./train_val/train
mkdir -p ./train_val/val
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/000' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/000.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/001' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/001.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/002' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/002.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/003' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/003.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/004' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/004.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/005' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/005.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/006' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/006.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/007' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/007.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/008' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/008.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/009' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/009.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/010' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/010.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/011' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/011.txt' 
find '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/openpose_data/Original_Data/012' -name "*.jpg" | tee '/media/pro/PRO/Ubuntu/Common_code/Data_preprocessing/train_val/012.txt' 
